---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Schedule for go module updates
  - package-ecosystem: "gomod"
    directory: "/common"
    schedule:
      interval: "daily"
      time: "18:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: all
    # a group of dependencies will be updated together in one pull request
    groups:
      golang:
        # group all semantic versioning levels together in one pull request
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/migration"
    schedule:
      interval: "daily"
      time: "18:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: all
    # a group of dependencies will be updated together in one pull request
    groups:
      golang:
        # group all semantic versioning levels together in one pull request
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/podmon"
    schedule:
      interval: "daily"
      time: "18:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: all
    # a group of dependencies will be updated together in one pull request
    groups:
      golang:
        # group all semantic versioning levels together in one pull request
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/replication"
    schedule:
      interval: "daily"
      time: "18:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: all
    # a group of dependencies will be updated together in one pull request
    groups:
      golang:
        # group all semantic versioning levels together in one pull request
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/volumeGroupSnapshot"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
    allow:
      # Allow direct updates for packages
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    # a group of dependencies will be updated together in one pull request
    groups:
      golang:
        # group all semantic versioning levels together in one pull request
        update-types:
          - major
          - minor
        patterns:
          - "*"

  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"
